version: '2'
services:
  db:
    image: mongo
  web:
    build: .
    command: /bin/bash /startup.sh
    # volumes: 
    #   - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
